name: Deploy to VPC

on:
  workflow_run:
    workflows: [Pylint]  # Name of the lint workflow to wait for
    branches: [main]       # Only run if the commit was on main
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deployment on VPC
        if: ${{ always() }}
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPC_HOST }}
          username: ${{ secrets.VPC_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            /home/nicknamemohaji/42seoul/inner-6/ft_transcendence/workflow.sh
